### ISSUE TITLE
Require binding from dtn host ip to dtn agent uri

### ISSUE THREAD

**Issue by fno2010** [openalto/alto-orchestrator#3]
For the demo, the URI can be a constant transform of dtn management IP. We still require the information of the mapping from the data transfer IP to the management IP.

**Comment by yjlcoder** [comment]
The orchestrator could look up the domain information from a given ip, and it can also get registered information. So you could add a field in the body of the post request.

**Comment by fno2010** [comment]
In current domain information schema, the `host` field is a list of `ipv4 address`.

We still require a `mangement ip` for each `host`.
